id: P24DD2D24
initial_creation_type: ocr
source_metadata:
  volumes:
    b61e22a9accb4481a2d7bae1afa02bac:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: དཱི་པཾ་ཀཱ་ར་ཤྲཱི་ཛྙཱ་ནའི་ཆོས་ཀྱི་གླུ།
      total_pages: 1953
      volume_number: 27
