id: DEA933222
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-06T09:34:35+00:00'
last_modified: '2022-05-26T11:31:39.022371+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    deac:
      image_group_id: I1PD95872
      title: དཱི་པཾ་ཀཱ་ར་ཤྲཱི་ཛྙཱ་ནའི་ཆོས་ཀྱི་གླུ།
      total_pages: 1953
      order: 27
      base_file: deac.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
